title: "Richard van Dieren"
description: "Private personal site"
url: "https://richardvd.github.io"   # or your project URL root
baseurl: ""                          # or "/repo-name" if project site
theme: null
markdown: kramdown
highlighter: none
plugins: []
exclude:
  - README.md
defaults:
  - scope:
      path: ""
    values:
      layout: null
      
